name: DevSecOps Pipeline - App & API Protection

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies and tools
      run: |
        pip install -r app/requirements.txt
        pip install bandit

    - name: Run Bandit (Static Code Analysis)
      run: bandit -r app -f txt -o bandit-report.txt

    - name: Build Docker Image
      run: docker build -t secure-api-ui .

    - name: Scan Docker Image with Trivy (Container Vulnerabilities)
      uses: aquasecurity/trivy-action@v0.6.0
      with:
        image-ref: 'secure-api-ui:latest'
      continue-on-error: true

    - name: Secret scan with Gitleaks
      uses: gitleaks/gitleaks-action@v2
      continue-on-error: true

    - name: Run OWASP ZAP Baseline Scan (DAST)
      uses: zaproxy/action-baseline@v0.11.0
      with:
        target: 'http://localhost:8000'
      continue-on-error: true

    - name: Deploy to Render (if on main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Trigger Render deployment here"
        # e.g., curl -X POST https://api.render.com/deploy/webservice/YOUR_SERVICE_ID -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
