name: "CodeQL"

on:
  push:
    branches: [ main, master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # runs weekly on Sundays at midnight UTC

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [ 'python' ]  # Change or add languages you want to scan

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1
      with:
        directory: ./infra
