name: ZAP Baseline Scan

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set write permissions
        run: sudo chmod -R 777 ${{ github.workspace }}

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: http://localhost:8000
          cmd_options: "-J report_json.json -w report_md.md -r report_html.html"
